src/Entity/Card.php
<?php

namespace App\Entity;

use App\Repository\CardRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CardRepository::class)
 */
class Card
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cardName;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=4, nullable=true)
     */
    private $attackValue;

    /**
     * @ORM\Column(type="string", length=4, nullable=true)
     */
    private $defenceValue;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $collectionID;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imgPath;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cardDescription;

    /**
     * @ORM\ManyToOne(targetEntity=CardAttribute::class, inversedBy="cards")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Attribute;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCardName(): ?string
    {
        return $this->cardName;
    }

    public function setCardName(string $cardName): self
    {
        $this->cardName = $cardName;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getAttackValue(): ?string
    {
        return $this->attackValue;
    }

    public function setAttackValue(?string $attackValue): self
    {
        $this->attackValue = $attackValue;

        return $this;
    }

    public function getDefenceValue(): ?string
    {
        return $this->defenceValue;
    }

    public function setDefenceValue(?string $defenceValue): self
    {
        $this->defenceValue = $defenceValue;

        return $this;
    }

    public function getCollectionID(): ?string
    {
        return $this->collectionID;
    }

    public function setCollectionID(string $collectionID): self
    {
        $this->collectionID = $collectionID;

        return $this;
    }

    public function getImgPath(): ?string
    {
        return $this->imgPath;
    }

    public function setImgPath(?string $imgPath): self
    {
        $this->imgPath = $imgPath;

        return $this;
    }

    public function getCardDescription(): ?string
    {
        return $this->cardDescription;
    }

    public function setCardDescription(?string $cardDescription): self
    {
        $this->cardDescription = $cardDescription;

        return $this;
    }

    public function getAttribute(): ?CardAttribute
    {
        return $this->Attribute;
    }

    public function setAttribute(?CardAttribute $Attribute): self
    {
        $this->Attribute = $Attribute;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Yugioh Collection Tracker{% endblock %}</title>
        <link rel="stylesheet" href="https://bootswatch.com/4/darkly/bootstrap.min.css">
    </head>
    <body>
        <div id="content">{% block content %}{% endblock %}</div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    </body>
</html>

templates/cardAddForm.html.twig
{% extends "base.html.twig" %}
{% block content %}
<div class='container-fluid'>
    <h1>Add a card to your collection</h1>
        <div class='row justify-content-start'>
        <div class='col-12'>
            <a href='/card/overview' class='btn btn-primary'>Return to overview</a>
        </div>
    </div>
    <hr>
    <div class='row'>
        <div class='col-12 justify-content-start'>
            <form method="post" action="/cardAdd/post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="cardName">Card name</label>
                    <input type="text" class="form-control" id="cardName" name="cardName" placeholder="Dark Magician" alt="A inputfield for the card name" required>
                </div>
                <div class="form-group">
                    <label for="cardType">Card Type</label>
                    <input type="text" class="form-control" id="cardType" name="cardType" placeholder="Spellcaster, Continuous spell, Counter trap" alt="A inputfield for the card type" required>
                </div>
                <div class="form-group">
                    <label for="cardAttribute">Card Attribute</label>
                    <select class="form-control" id="cardAttribute" name="cardAttribute" alt="A inputfield for the card Attribute">
                        <option value="1" style="background-image:url({{ asset('cardAttributeIMG/DARK.png') }});">Dark</option>
                        <option value="2">Divine</option>
                        <option value="3">Earth</option>
                        <option value="4">Fire</option>
                        <option value="5">Light</option>
                        <option value="6">Water</option>
                        <option value="7">Wind</option>
                        <option value="8">Spell</option>
                        <option value="9">Trap</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="cardAttackValue">Card Attack Value (Only applies for monster cards)</label>
                    <input type="text" class="form-control" id="cardAttackValue" name="cardAttackValue" placeholder="2500" alt="A inputfield for the card Attack value if possible">
                </div>
                <div class="form-group">
                    <label for="cardDefenceValue">Card Defence Value (Only applies for monster cards)</label>
                    <input type="text" class="form-control" id="cardDefenceValue" name="cardDefenceValue" placeholder="2000" alt="A inputfield for the card Defence value if possible">
                </div>
                <div class="form-group">
                    <label for="cardDescription">Card Descriptiom (The flavour text or effect on the card)</label>
                    <input type="text" class="form-control" id="cardDescription" name="cardDescription" placeholder="The ultimate wizard in terms of attack and defense." alt="A inputfield for the card Description(flavour text or effect)">
                </div>
                <div class="form-group">
                    <label for="cardCollectionID">Card Collection Code</label>
                    <input type="text" class="form-control" id="cardCollectionID" name="cardCollectionID" placeholder="SYE-001" alt="A inputfield for the card Collection Code" required>
                </div>
                <div class="form-group">
                    <label for="CardImage">Card Image</label>
                    <input type="file" class="form-control-file" id="cardImage" name="cardImage"  accept="image/*">
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-success" value="Add">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/cardDetails.html.twig
{% extends "base.html.twig" %}
{% block content %}
<div class='container-fluid'>
    <h1>Card Detail</h1>
    <div class='row justify-content-start'>
        <div class='col-12'>
            <a href='/card/overview' class='btn btn-primary'>Return to overview</a>
        </div>
    </div>
    <hr>
    <div class='row'>
        <div class='col-12 justify-content-start'>
            <table class='col-12 table table-dark table-bordered'>
                <thead>
                    <tr>
                        <th>Card name</th>
                        <th>Type</th>
                        <th>Attribute</th>
                        <th>Attack Value</th>
                        <th>Defence Value</th>
                        <th>Card Description</th>
                        <th>Card collection code</th>
                        <th>Card Image</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{card.cardName}}</td>
                        <td>{{card.type}}</td>
                        <td>{{card.attribute}}</td>
                        <td>{{card.attackValue}}</td>
                        <td>{{card.defenceValue}}</td>
                        <td>{{card.cardDescription}}</td>
                        <td>{{card.collectionID}}</td>
                        <td>{% if card.imgPath %}<img src="{{ asset('uploads/') ~ card.imgPath }}" alt='img of the card {{card.cardName}}'> {% else %} No image available {% endif %}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/cardOverview.html.twig
{% extends "base.html.twig" %}
{% block content %}
<div class='container-fluid'>
    <h1>Welcome to the Yu-Gi-Oh! collection tracker</h1>
    <div class='row justify-content-start'>
        <div class='col-12'>
            <a href='/card/addForm' class='btn btn-primary'>Add card</a>
        </div>
    </div>
    <hr>
    <div class='row'>
        <div class='col-12 justify-content-start'>
            <table class='col-12 table table-dark'>
                <thead>
                    <tr>
                        <th>Card name</th>
                        <th>Type</th>
                        <th>Attribute</th>
                        <th>Attack Value</th>
                        <th>Defence Value</th>
                        <th>Card Description</th>
                        <th>Card collection code</th>
                    </tr>
                </thead>
                <tbody>
                {% for card in registeredCards %}
                    <tr>
                        <td>{{card.cardName}}</td>
                        <td>{{card.type}}</td>
                        <td style="text-align: center"><img src="{{ asset('cardAttributeIMG/') ~ card.attribute.attributeImagePath }}" alt='img of the card {{card.cardName}}'></td>
                        <td>{{card.attackValue}}</td>
                        <td>{{card.defenceValue}}</td>
                        <td>{{card.cardDescription}}</td>
                        <td>{{card.collectionID}}</td>
                        <td><a href='/card/detail/{{card.id}}' class="btn btn-primary">Details</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}